=== SrirangaDigital/bvb/bvb.dtd
<!ELEMENT bhavans (volume*)>
<!ELEMENT volume (part*)>
<!ATTLIST volume vnum CDATA #REQUIRED>
<!ELEMENT part (entry+)>
<!ATTLIST part pnum CDATA #REQUIRED>
<!ATTLIST part date CDATA #REQUIRED>
<!ATTLIST part month CDATA #REQUIRED>
<!ATTLIST part year CDATA #REQUIRED>
<!ATTLIST part cover CDATA #REQUIRED>
<!ELEMENT entry (title,feature,series,page,allauthors)>
<!ELEMENT title ANY>
<!ELEMENT i ANY>
<!ATTLIST title num CDATA #REQUIRED>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT series (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT allauthors (author*)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author type CDATA #REQUIRED>

=== SrirangaDigital/bvb/bvb-prathi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bhavans SYSTEM "bvb.dtd">

<bhavans>
	<volume vnum="060">
		<part pnum="08" date="30" month="11" year="2013" cover="Manna Dey">
			<entry>
				<title num="">Bestowed Power</title>
				<feature>Sage Speak</feature>
				<series />
				<page>0001-0001</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Flash Back : Bhavan's Journal, Fifty years ago</title>
				<feature>Flash Back</feature>
				<series />
				<page>0006-0007</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Reader.com : Kulapativan</title>
				<feature />
				<series />
				<page>0008-0010</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">The Way of The Spirit</title>
				<feature>Kulapativani</feature>
				<series />
				<page>0011-0011</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">The Purpose and Need for Puranas</title>
				<feature>A Letter from the Bhavan's President</feature>
				<series />
				<page>0012-0013</page>
				<allauthors>
					<author type="0">Mehta, Surendralal G.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Manna Da, Your `<i>Sur Ke Beena Jivan Soona</i>'</title>
				<feature />
				<series />
				<page>0014-0017</page>
				<allauthors>
					<author type="0">Narayanam, V. N.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Gandhian View of Education</title>
				<feature />
				<series />
				<page>0018-0024</page>
				<allauthors>
					<author type="0">Kumar, Ravindra</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Guru Nanak He Delivered the Words of God</title>
				<feature />
				<series />
				<page>0025-0032</page>
				<allauthors>
					<author type="0">Duggal, K. S.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Education for the Future</title>
				<feature>Bhavan's Essay</feature>
				<series />
				<page>0033-0039</page>
				<allauthors>
					<author type="0">Hegde, B. M.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Adi Sankara-Preceptor of Advaita Vedanta</title>
				<feature />
				<series />
				<page>0041-0045</page>
				<allauthors>
					<author type="0">Behera, Radhanath</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Dronacharya &amp; Ekalavya</title>
				<feature />
				<series />
				<page>0046-0049</page>
				<allauthors>
					<author type="0">Shenoi, Saratchandra</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Swami Shivananda Founder of `Divine Life Society', Rishikesh</title>
				<feature />
				<series />
				<page>0050-0053</page>
				<allauthors>
					<author type="0">Murthy, B. M. N.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">I Crave for that Freedom !!</title>
				<feature />
				<series />
				<page>0054-0054</page>
				<allauthors>
					<author type="0">Mathur, Aastha</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Safety of Predestrians is Human Right</title> 
				<feature />
				<series />
				<page>0055-0058</page>
				<allauthors>
					<author type="0">Jain, A. K.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Near Death Experience</title>
				<feature />
				<series />
				<page>0059-0069</page>
				<allauthors>
					<author type="0">Gopinath, N.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">In Defence of Karna</title>
				<feature />
				<series />
				<page>0070-0077</page>
				<allauthors>
					<author type="0">Razdan, B. L.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Swadhyaya : Valmiki Ramayana (Uttarakanada, Canto 45)</title>
				<feature>Valmiki Ramayana</feature>
				<series />
				<page>0078-0079</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Tales of Strength</title>
				<feature>Book Shelf</feature>
				<series />
				<page>0081-0087</page>
				<allauthors>
					<author type="0">Vindhya</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Chetana</title>
				<feature>Chetana</feature>
				<series />
				<page>0088-0089</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Nandana</title>
				<feature>Nandana</feature>
				<series />
				<page>0091-0093</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Rank Holders</title>
				<feature />
				<series />
				<page>0095-0101</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Platinum Jubilee Lecture Series : Five Sutras that Guid Bhavan</title>
				<feature />
				<series />
				<page>0102-0104</page>
				<allauthors>
					<author type="0">Singh, Dr. Karan</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Bhavan's News</title>
				<feature>Bhavan's News</feature>
				<series />
				<page>0105-0112</page>
				<allauthors />
			</entry>
		</part>
		<part pnum="14" date="28" month="02" year="2014" cover="Mauritius-Sparkling Crystal in Indian Ocean">
			<entry>
				<title num="">Sage Speak : Each must Assimilate the Spirit of the others</title>
				<feature>Sage Speak</feature>
				<series />
				<page>0001-0001</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Flash Back : Bhavan's Journal, Fifty years ago</title>
				<feature>Flash Back</feature>
				<series />
				<page>0006-0007</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Reader.com</title>
				<feature>Reader.com</feature>
				<series />
				<page>0008-0010</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Sankara Bhagavatpada</title>
				<feature>Kulapativani</feature>
				<series />
				<page>0011-0011</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">From the President : Imagination-The Key to Creativity</title>
				<feature>A Letter from the Bhavan's President</feature>
				<series />
				<page>0012-0013</page>
				<allauthors>
					<author type="0">Mehta, Surendralal G.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">The Power of Vote Lies in Casting it</title>
				<feature>Editorial</feature>
				<series />
				<page>0014-0015</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Dr. Radhakrishnan's Association with the Bhavan</title>
				<feature />
				<series />
				<page>0017-0024</page>
				<allauthors>
					<author type="0">Behera, Radhanath</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Salt Satyagraha: Dandi's Place in History</title>
				<feature />
				<series />
				<page>0025-0031</page>
				<allauthors>
					<author type="0">Mishra, Ramachandra</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Values in Life and Education</title>
				<feature />
				<series />
				<page>0033-0040</page>
				<allauthors>
					<author type="0">Dubashi, P. R.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Vivekananda and Challenges of 21st Century</title>
				<feature />
				<series />
				<page>0041-0045</page>
				<allauthors>
					<author type="0">Sudarshananda, Swami</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Towards a Consciousness of Unity</title>
				<feature />
				<series />
				<page>0046-0056</page>
				<allauthors>
					<author type="0">Tompkins, Lori</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Mauritius : Sparkling Crystal in Indian Ocean</title>
				<feature />
				<series />
				<page>0057-0066</page>
				<allauthors>
					<author type="0">Menon, Pachu</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">On Reaching the Clarke Orbit</title>
				<feature />
				<series />
				<page>0067-0072</page>
				<allauthors>
					<author type="0">Rajan, Mohan Sundara</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Gayatri Mantra : Its Significance</title>
				<feature />
				<series />
				<page>0073-0075</page>
				<allauthors>
					<author type="0">Murthy, B. M. N.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Five Steps to Turn Wishes into Goals</title>
				<feature />
				<series />
				<page>0076-0078</page>
				<allauthors>
					<author type="0">Iyer, T. G. L.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Scientific Agnostics : Think Out of the Box</title>
				<feature />
				<series />
				<page>0079-0082</page>
				<allauthors>
					<author type="0">Hegde, B. M.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">The Spirit of Silence</title>
				<feature />
				<series />
				<page>0083-0084</page>
				<allauthors>
					<author type="0">Vaswani, Sadhu</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Spirituality and Religion</title>
				<feature />
				<series />
				<page>0085-0087</page>
				<allauthors>
					<author type="0">Sreenivas, Venkatachala I.</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Swadhyaya : Valmiki Ramayana (Uttarakanda, Canto 46)</title>
				<feature>Valmiki Ramayana</feature>
				<series />
				<page>0088-0089</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Movers and `Shapers'</title>
				<feature>Book Shelf</feature>
				<series />
				<page>0090-0097</page>
				<allauthors>
					<author type="0">Vindhya</author>
				</allauthors>
			</entry>
			<entry>
				<title num="">Chetana</title>
				<feature>Chetana</feature>
				<series />
				<page>0099-0103</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Nandana</title>
				<feature>Nandana</feature>
				<series />
				<page>0104-0107</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Rank Holders</title>
				<feature />
				<series />
				<page>0108-0113</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Homage to the Departed</title>
				<feature>Homage</feature>
				<series />
				<page>0114-0114</page>
				<allauthors />
			</entry>
			<entry>
				<title num="">Recent Happening : Baldarbar at Nagpur</title>
